stages:
 - test
 - staging
 - production

before_script:
 - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
 - eval $(ssh-agent -s)
 - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
 - mkdir -p ~/.ssh
 - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
 - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

test:
  stage: test
  script:
    - ssh $SSH_USER@$SSH_URL "cd $DEV_PATH &&
          git pull origin develop && php wp-cli.phar plugin update --all && php wp-cli.phar language plugin update -all"
  environment:
     name: development
     url: https://$DEV_URL
  only:
     - develop

staging:
  stage: staging
  script:
    - ssh $SSH_USER@$SSH_URL "cd $STAG_PATH &&
          git pull origin staging  && php wp-cli.phar plugin update --all && php wp-cli.phar language plugin update -all"
  environment:
     name: development
     url: https://$STAG_URL
  only:
     - staging

production:
  stage: production
  script:
   - ssh $SSH_USER@$SSH_URL "cd $PROD_PATH &&
          git pull origin master"
  environment:
    name: production
    url: https://$PROD_URL
  only:
   - master
